package main

import (
	"fmt"
	"strings"
)

// runExport prints a mac.toml derived from the current system state to stdout.
func runExport(r Runner) {
	fmt.Print(generateExportTOML(r))
}

// generateExportTOML reads current Homebrew and machine state and returns a
// commented mac.toml suitable for use as a starting point.
func generateExportTOML(r Runner) string {
	// Machine identity
	computerName, _ := r.Run("scutil", "--get", "ComputerName")
	localHostname, _ := r.Run("scutil", "--get", "LocalHostName")
	if computerName == "" {
		computerName, _ = r.Run("hostname", "-s")
	}
	if localHostname == "" {
		localHostname = computerName
	}

	// Homebrew state
	formulaeOut, _ := r.Run("brew", "list", "--formula", "-1")
	casksOut, _ := r.Run("brew", "list", "--cask", "-1")
	tapsOut, _ := r.Run("brew", "tap")

	formulae := exportLines(formulaeOut)
	casks := exportLines(casksOut)
	taps := exportLines(tapsOut)

	var b strings.Builder

	fmt.Fprintln(&b, "# ============================================================================")
	fmt.Fprintln(&b, "# mac.toml — generated by: mac export")
	fmt.Fprintln(&b, "# Edit this file, then run:  mac apply")
	fmt.Fprintln(&b, "# Full reference: https://github.com/idioticdev/mac#config-reference")
	fmt.Fprintln(&b, "# ============================================================================")
	fmt.Fprintln(&b)

	// Machine
	fmt.Fprintln(&b, "[machine]")
	fmt.Fprintf(&b, "computer_name  = %q\n", computerName)
	fmt.Fprintf(&b, "local_hostname = %q\n", localHostname)
	fmt.Fprintln(&b)

	// Packages
	fmt.Fprintln(&b, "[packages]")
	if len(formulae) == 0 {
		fmt.Fprintln(&b, "formulae = []")
	} else {
		fmt.Fprintln(&b, "formulae = [")
		for _, f := range formulae {
			fmt.Fprintf(&b, "    %q,\n", f)
		}
		fmt.Fprintln(&b, "]")
	}
	fmt.Fprintln(&b)
	if len(casks) == 0 {
		fmt.Fprintln(&b, "casks = []")
	} else {
		fmt.Fprintln(&b, "casks = [")
		for _, c := range casks {
			fmt.Fprintf(&b, "    %q,\n", c)
		}
		fmt.Fprintln(&b, "]")
	}
	fmt.Fprintln(&b)
	if len(taps) > 0 {
		fmt.Fprintln(&b, "taps = [")
		for _, t := range taps {
			fmt.Fprintf(&b, "    %q,\n", t)
		}
		fmt.Fprintln(&b, "]")
		fmt.Fprintln(&b)
	}

	// Dotfiles stub
	fmt.Fprintln(&b, "# ── Dotfiles (uncomment and fill in) ───────────────────────────────────────")
	fmt.Fprintln(&b, "# [dotfiles]")
	fmt.Fprintln(&b, "# repo          = \"git@github.com:you/dotfiles.git\"")
	fmt.Fprintln(&b, "# dest          = \"~/.dotfiles\"")
	fmt.Fprintln(&b, "# method        = \"stow\"")
	fmt.Fprintln(&b, "# stow_packages = [\"zsh\", \"git\", \"nvim\"]")
	fmt.Fprintln(&b)

	// Shell stub
	fmt.Fprintln(&b, "# ── Default shell ──────────────────────────────────────────────────────────")
	fmt.Fprintln(&b, "# [shell]")
	fmt.Fprintln(&b, "# default = \"/bin/zsh\"")
	fmt.Fprintln(&b)

	// System
	fmt.Fprintln(&b, "# ── System tweaks ──────────────────────────────────────────────────────────")
	fmt.Fprintln(&b, "# [system]")
	fmt.Fprintln(&b, "# pam_tid        = true   # Touch ID for sudo")
	fmt.Fprintln(&b, "# reveal_library = true   # Unhide ~/Library")
	fmt.Fprintln(&b)

	// Hooks stub
	fmt.Fprintln(&b, "# ── Post-install hooks ─────────────────────────────────────────────────────")
	fmt.Fprintln(&b, "# [hooks]")
	fmt.Fprintln(&b, "# post_install = [")
	fmt.Fprintln(&b, "#     \"softwareupdate --install-rosetta --agree-to-license 2>/dev/null || true\",")
	fmt.Fprintln(&b, "# ]")
	fmt.Fprintln(&b)

	// nix-darwin note
	fmt.Fprintln(&b, "# ── nix-darwin users ────────────────────────────────────────────────────────")
	fmt.Fprintln(&b, "# If nix-darwin manages machine identity, shell, or system settings,")
	fmt.Fprintln(&b, "# add a [meta] section so mac doesn't fight nix-darwin for control:")
	fmt.Fprintln(&b, "#")
	fmt.Fprintln(&b, "#   [meta]")
	fmt.Fprintln(&b, "#   skip = [\"machine\", \"shell\", \"system\"]")
	fmt.Fprintln(&b, "#")
	fmt.Fprintln(&b, "# Run:  mac diff    to preview changes before applying.")

	return b.String()
}

// exportLines splits newline-separated output into a non-empty slice of strings.
// Returns nil (not []string{""}) when the input is empty.
func exportLines(s string) []string {
	var lines []string
	for _, line := range strings.Split(strings.TrimSpace(s), "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			lines = append(lines, line)
		}
	}
	return lines
}
